### ISSUE TITLE
Update to Vultr's V2 api 

### ISSUE THREAD

**Issue by ugjka** [undecidabot/certbot-dns-vultr#1]
![Screenshot_20230421_180216](https://user-images.githubusercontent.com/13318673/233795425-44a03b4e-b4ea-4f9b-9b32-97f3fa7e7b12.png)

**Comment by lezgomatt** [comment]
Hey @ugjka, thanks for the bug report! I'm a bit busy at the moment, but I'll try to find time to work on this soon 🙂
