### ISSUE TITLE
Update vultr api to v2

### ISSUE THREAD

**Issue by clord** [undecidabot/certbot-dns-vultr#3]
I'm getting this output, and I believe it's coming from [this line](https://github.com/lezgomatt/certbot-dns-vultr/blob/764f5149c8960fb38afbd3c81b155f9b396d5e29/certbot_dns_vultr.py#L101).

> Error fetching DNS domains list: 503 - Sorry, all newly created accounts are forbidden from using API v1, all other accounts are able to use this deprecated API until September 30, 2023 at which point Vultr API v1 will be sunset. Please use API v2.

https://www.vultr.com/docs/vultr-api-v1-to-v2-transition-strategies/

**Comment by clord** [comment]
Sorry, I just noticed this is fixed with this PR:
https://github.com/lezgomatt/certbot-dns-vultr/pull/2

is the PR released?

**Comment by lezgomatt** [comment]
Hey @clord, that fix should already be released in v1.1.0. You can check the package you have installed using `pip show certbot-dns-vultr`.

Please let me know if it's still an issue after upgrading.

**Comment by clord** [comment]
Works locally, thanks.
